import { countryFlagEmoji } from "@/lib/constants/countries";

// Maps an ISO 639-1 language code to one representative country (for a small flag icon next to
// the language name on the Dashboard's language-distribution chart). A language isn't tied to a
// single country the way a timezone is, so this is a deliberate, subjective pick — generally the
// country most associated with the language's origin or largest audience. Languages not listed
// here simply render without a flag; there's no "correct" single country for e.g. Arabic or
// Kurdish, so guessing one would be misleading.
const LANGUAGE_COUNTRY: Record<string, string> = {
  af: "ZA",
  am: "ET",
  ar: "SA",
  az: "AZ",
  be: "BY",
  bg: "BG",
  bn: "BD",
  bs: "BA",
  ca: "ES",
  cs: "CZ",
  cy: "GB",
  da: "DK",
  de: "DE",
  el: "GR",
  en: "US",
  es: "ES",
  et: "EE",
  eu: "ES",
  fa: "IR",
  fi: "FI",
  fil: "PH",
  fr: "FR",
  ga: "IE",
  gl: "ES",
  gu: "IN",
  he: "IL",
  hi: "IN",
  hr: "HR",
  ht: "HT",
  hu: "HU",
  hy: "AM",
  id: "ID",
  is: "IS",
  it: "IT",
  ja: "JP",
  jv: "ID",
  ka: "GE",
  kk: "KZ",
  km: "KH",
  kn: "IN",
  ko: "KR",
  ky: "KG",
  lo: "LA",
  lt: "LT",
  lv: "LV",
  mg: "MG",
  mk: "MK",
  ml: "IN",
  mn: "MN",
  mr: "IN",
  ms: "MY",
  mt: "MT",
  my: "MM",
  nb: "NO",
  ne: "NP",
  nl: "NL",
  nn: "NO",
  no: "NO",
  or: "IN",
  pa: "IN",
  pl: "PL",
  ps: "AF",
  pt: "PT",
  ro: "RO",
  ru: "RU",
  sd: "PK",
  si: "LK",
  sk: "SK",
  sl: "SI",
  sq: "AL",
  sr: "RS",
  sv: "SE",
  sw: "TZ",
  ta: "IN",
  te: "IN",
  th: "TH",
  tl: "PH",
  tr: "TR",
  uk: "UA",
  ur: "PK",
  uz: "UZ",
  vi: "VN",
  zh: "CN",
  zu: "ZA",
};

export function languageFlagEmoji(languageCode: string): string {
  const country = LANGUAGE_COUNTRY[languageCode];
  return country ? countryFlagEmoji(country) : "";
}
